export { Home } from './Home'
export { Calculator } from './Calculator'
export { Education } from './Education'
export { About } from './About'
export { Privacy } from './Privacy'
export { Disclaimer } from './Disclaimer'
export { Settings } from './Settings'
